import math
import random


class PriceSimulator:
    """
    A class for simulating price data with noise and spikes.

    Methods:
    - price_envelope(num_intervals, min_price, max_price, peak_start, peak_end): Generate price data with a smooth envelope curve for peak and off-peak prices.
    - add_noise_and_spikes(prices, noise_level, spike_chance, spike_multiplier): Adds random noise and occasional spikes to the prices.
    """

    @staticmethod
    def price_envelope(
        num_intervals=48, min_price=15, max_price=30, peak_start=16, peak_end=32
    ) -> list:
        """
        Generate price data with a smooth envelope curve for peak and off-peak prices.

        Parameters:
        - num_intervals (int): The number of price intervals (assuming 30 minutes per interval for a 24-hour day).
        - min_price (float): The minimum price during off-peak hours.
        - max_price (float): The maximum price during peak hours.
        - peak_start (int): The interval index for the start of peak pricing.
        - peak_end (int): The interval index for the end of peak pricing.

        Returns:
        List[float]: A list of prices with a smooth transition between off-peak and peak hours.
        """
        prices = []
        for i in range(num_intervals):
            # Calculate the position of the current interval within the cycle
            x = (math.pi * 2) * (i / num_intervals)
            # Generate a sine wave for smooth transitions
            sine_value = (
                math.sin(x - math.pi / 2) + 1
            ) / 2  # Scale sine wave to [0, 1]
            price = min_price + (max_price - min_price) * sine_value

            # Keep prices at min_price outside of peak hours
            if i < peak_start or i >= peak_end:
                price = min_price

            prices.append(price)
        return prices

    @staticmethod
    def add_noise_and_spikes(
        prices, noise_level=5, spike_chance=0.05, spike_multiplier=1.5
    ):
        """
        Adds random noise and occasional spikes to the prices.

        Parameters:
        - prices (list): The original list of prices generated by price_envelope.
        - noise_level (float): The maximum deviation added as noise to each price point.
        - spike_chance (float): The probability of a price spike occurring at any interval.
        - spike_multiplier (float): The factor by which prices increase during a spike.

        Returns:
        List[float]: The modified list of prices with added noise and spikes.
        """
        noisy_prices = []
        for price in prices:
            # Add random noise
            noise = random.uniform(-noise_level, noise_level)
            new_price = price + noise

            # Randomly introduce spikes
            if random.random() < spike_chance:
                new_price *= spike_multiplier

            # Ensure the price does not go negative
            new_price = max(0, new_price)
            noisy_prices.append(new_price)

        return noisy_prices
