name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Important: fetch all history for all tags and branches

    # Fetch tags to ensure we can compute the latest tag/version
    - name: Fetch tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    # Set the latest version as an environment variable
    - name: Get the latest tag
      id: get_version
      run: echo "VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

    # Optionally, print the version for verification
    - name: Print version
      run: echo "Version of the codebase is $VERSION"

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.13'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda install -y python=3.10.13
        conda env update --file environment.yml --name base 

    - name: Linting check with Ruff
      run: |
        ruff check scripts/
        ruff check app.py

    - name: Running Pytest
      run: | 
        pytest

    - name: Running mypy
      run: | 
        mypy scripts/
        mypy app.py
